export const caseStudies = {
  "w-steak": {
    title: "W Steak Restaurant · v1",
    kind: "concept",
    type: "UI/UX Redesign Concept",
    tags: ["HTML", "Dark & Gold", "Hospitality"],
    official: "https://wrestaurant.cz/",
    beforeImage: "case-studies/before-w-steak.jpg",
    demo: "https://zirvey.github.io/w-steak-restaurant-landing-page/",
    github: "https://github.com/Zirvey/w-steak-restaurant-landing-page",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/w-steak-restaurant-landing-page/main/docs/screenshots/hero-desktop.jpg",
    challenge:
      "The official W Steak Restaurant site carries strong brand recognition but the landing experience felt dated — dense layout, limited visual hierarchy, and a mobile experience that didn't match the premium positioning of a steak & whiskey bar in Prague.",
    approach: [
      "Audited the original wrestaurant.cz structure, menu flow, and reservation path",
      "Defined a dark & gold design system aligned with the restaurant's premium identity",
      "Built a bento-grid hero, experience section, menu highlights, and about block",
      "Prioritised mobile-first responsive layout with clear CTAs for reservations",
    ],
    results: [
      "Cohesive premium dark aesthetic with gold accent system",
      "Clear information hierarchy from hero → experience → menu → contact",
      "Fully responsive concept deployed to GitHub Pages",
      "Reused official photography and menu data for realistic demonstration",
    ],
    stack: "HTML, CSS, Vanilla JS",
    ru: {
      type: "UI/UX концепт редизайна",
      challenge:
        "Официальный сайт W Steak Restaurant узнаваем, но лендинг выглядел устаревшим — плотная вёрстка, слабая визуальная иерархия и мобильный опыт, который не соответствовал премиум-позиции стейк- и виски-бара в Праге.",
      approach: [
        "Разобрал структуру wrestaurant.cz, путь по меню и бронированию",
        "Собрал тёмно-золотую дизайн-систему под премиум-идентичность ресторана",
        "Сделал bento-hero, блок опыта, акценты меню и about-секцию",
        "Приоритизировал mobile-first вёрстку с понятными CTA на бронирование",
      ],
      results: [
        "Цельный премиум dark-эстетик с золотой акцент-системой",
        "Ясная иерархия: hero → опыт → меню → контакты",
        "Полностью адаптивный концепт на GitHub Pages",
        "Официальные фото и данные меню для реалистичной демонстрации",
      ],
    },
  },
  "w-steak-v2": {
    title: "W Steak · Editorial",
    kind: "concept",
    type: "Concept Redesign",
    tags: ["HTML", "Editorial", "Hospitality"],
    official: "https://wrestaurant.cz/",
    beforeImage: "case-studies/before-w-steak.jpg",
    demo: "https://zirvey.github.io/w-steak-restaurant-landing-page-v2/",
    github: "https://github.com/Zirvey/w-steak-restaurant-landing-page-v2",
    afterImage: "projects/w-steak-editorial.jpg",
    challenge:
      "W Steak Restaurant in Prague has a strong brand, but the site didn’t feel as premium as the steak & whiskey experience. This concept redesign explores a warm editorial direction — parchment, saffron, and typography-led hierarchy — instead of a dark luxury look.",
    approach: [
      "Audited wrestaurant.cz content with a parchment-and-saffron editorial lens",
      "Defined a warm canvas system: sharp edges, saffron accent, typography-led hierarchy",
      "Built hero, experience, menu, and about sections with scroll-driven editorial rhythm",
      "Prioritised mobile-first responsive layout with clear reservation CTAs",
    ],
    results: [
      "A cohesive editorial concept redesign for a real steak restaurant brand",
      "Warm hospitality feel without losing premium positioning",
      "Fully responsive concept with desktop and mobile screenshots",
      "Live GitHub Pages demo for portfolio presentation",
    ],
    stack: "HTML, CSS, Vanilla JS",
    ru: {
      type: "Концепт редизайна",
      challenge:
        "У W Steak Restaurant в Праге сильный бренд, но сайт не звучал так же премиально, как сам стейк- и виски-бар. Этот концепт редизайна исследует тёплый editorial-подход — пергамент, шафран и типографическая иерархия — вместо тёмной роскоши.",
      approach: [
        "Разобрал контент wrestaurant.cz через editorial-линзу: пергамент и шафран",
        "Задал тёплую canvas-систему: острые края, шафрановый акцент, типографическая иерархия",
        "Собрал hero, опыт, меню и about со scroll-driven editorial-ритмом",
        "Приоритизировал mobile-first вёрстку с понятными CTA на бронирование",
      ],
      results: [
        "Цельный editorial-концепт редизайна для реального стейк-ресторана",
        "Тёплое hospitality-ощущение без потери премиум-позиции",
        "Полностью адаптивный концепт со скриншотами desktop и mobile",
        "Живое демо на GitHub Pages для портфолио",
      ],
    },
  },
  smokehouse: {
    title: "Smokehouse Prague",
    kind: "concept",
    type: "UI/UX Redesign Concept",
    tags: ["Next.js", "Framer Motion", "Hospitality"],
    official: "https://www.smokehouse.cz/",
    beforeImage: "case-studies/before-smokehouse.jpg",
    demo: "https://zirvey.github.io/smokehouse-desing/",
    github: "https://github.com/Zirvey/smokehouse-desing",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/smokehouse-desing/main/docs/hero.png",
    challenge:
      "Smokehouse operates three Prague locations with a loyal audience, but the existing website didn't convey the lounge's premium atmosphere — navigation was cluttered and animations were absent, making the brand feel static online.",
    approach: [
      "Studied smokehouse.cz content architecture across locations and loyalty program",
      "Preserved Czech copy and original brand assets for authenticity",
      "Designed scroll-driven sections: hero, features, locations, loyalty, CTA",
      "Implemented Framer Motion micro-interactions and Tailwind v4 layout system",
    ],
    results: [
      "Modern dark lounge aesthetic with gold accents and smooth entrance animations",
      "Multi-location content organised in a scannable layout",
      "Production-grade Next.js 15 + TypeScript codebase with CI pipeline",
      "Deployed live demo on GitHub Pages",
    ],
    stack: "Next.js 15, TypeScript, Tailwind CSS v4, Framer Motion",
    ru: {
      type: "UI/UX концепт редизайна",
      challenge:
        "У Smokehouse три локации в Праге и лояльная аудитория, но сайт не передавал премиум-атмосферу лаунжа — навигация была перегружена, анимаций не было, и бренд выглядел статично онлайн.",
      approach: [
        "Изучил архитектуру smokehouse.cz по локациям и программе лояльности",
        "Сохранил чешский копирайт и оригинальные бренд-ассеты",
        "Спроектировал scroll-driven секции: hero, фичи, локации, лояльность, CTA",
        "Внедрил микроинтеракции на Framer Motion и layout-систему на Tailwind v4",
      ],
      results: [
        "Современный dark lounge-эстетик с золотыми акцентами и плавными входами",
        "Контент по нескольким локациям в удобной для сканирования структуре",
        "Production-grade код на Next.js 15 + TypeScript с CI",
        "Живое демо на GitHub Pages",
      ],
    },
  },
  "smoky-place": {
    title: "Smoky Place",
    kind: "concept",
    type: "UI/UX Redesign Concept",
    tags: ["HTML", "Dark & Red", "Hospitality"],
    official: "https://smokyplace.cz/",
    beforeImage: "case-studies/before-smoky-place.jpg",
    demo: "https://zirvey.github.io/smoky-place-landing-page/",
    github: "https://github.com/Zirvey/smoky-place-landing-page",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/smoky-place-landing-page/main/docs/screenshots/hero.png",
    challenge:
      "Smoky Place is a hookah lounge at Prague Chodov with a distinctive brand, but the current site lacked visual impact — key offerings like the VIP lounge, events, and reviews were buried without strong calls to action.",
    approach: [
      "Mapped smokyplace.cz user journey: discovery → menu → VIP lounge → booking",
      "Created a red-accent dark theme with glowing coal hero imagery",
      "Designed dedicated sections for menu, private lounge, events calendar, and reviews carousel",
      "Built reservation modal and sticky navigation for mobile users",
    ],
    results: [
      "Premium hookah lounge feel with red & gold accent palette",
      "VIP lounge and events promoted as first-class sections",
      "Czech-localised content with scroll animations and responsive layout",
      "Live GitHub Pages demo ready for portfolio presentation",
    ],
    stack: "HTML, CSS, Vanilla JS",
    ru: {
      type: "UI/UX концепт редизайна",
      challenge:
        "Smoky Place — кальянная на Chodov в Праге с узнаваемым брендом, но сайт не давал визуального удара: VIP-лаунж, ивенты и отзывы были спрятаны без сильных призывов к действию.",
      approach: [
        "Составил user journey smokyplace.cz: discovery → меню → VIP → бронирование",
        "Сделал dark-тему с красным акцентом и glowing coal в hero",
        "Выделил секции меню, private lounge, календаря ивентов и карусели отзывов",
        "Собрал модалку бронирования и sticky-навигацию для мобильных",
      ],
      results: [
        "Премиум-ощущение кальянной с красно-золотой палитрой",
        "VIP-лаунж и ивенты как первоклассные секции",
        "Чешская локализация, scroll-анимации и адаптивная вёрстка",
        "Живое демо на GitHub Pages для портфолио",
      ],
    },
  },
  booking: {
    title: "Booking Telegram App",
    kind: "product",
    type: "Full-Stack Product",
    tags: ["Telegram Mini App", "PostgreSQL", "White-label"],
    official: null,
    demo: "https://zirvey.github.io/Booking-Telegram-App-Prewiev/",
    github: "https://github.com/Zirvey/Booking-Telegram-App-Prewiev",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/Booking-Telegram-App-Prewiev/main/docs/screenshots/general/hero-banner.png",
    challenge:
      "Service businesses — trainers, barbers, tutors, therapists — lose clients in messy DMs and miss appointments. They need a turnkey booking system without hiring a dev team or building a website from scratch.",
    approach: [
      "Defined the product idea, user flows, and white-label positioning from scratch",
      "Built the full backend: PostgreSQL, scheduling logic, Google Calendar sync, reminders",
      "Developed Telegram Bot + Mini App frontend with niche-specific UI themes",
      "Shipped admin panel, role-based access, multi-language support, and health monitoring",
      "Created an interactive demo site for client presentations and onboarding",
    ],
    results: [
      "End-to-end product — from idea to deployable solution",
      "2–3 tap booking flow inside Telegram, no separate website required",
      "White-label themes per niche (trainer, barber, tutor) — not a generic template",
      "Production-ready stack with automated monitoring on Railway/Vercel",
    ],
    stack: "Telegram Bot API, Mini App, PostgreSQL, Google Calendar, Python, Vercel",
    role: "Product idea, UI/UX, backend, frontend, deployment",
    ru: {
      type: "Full-Stack продукт",
      role: "Идея продукта, UI/UX, backend, frontend, деплой",
      challenge:
        "Сервисный бизнес — тренеры, барберы, репетиторы, терапевты — теряет клиентов в хаотичных личных сообщениях и пропускает записи. Нужна готовая система бронирования без найма команды и сайта с нуля.",
      approach: [
        "С нуля определил идею продукта, user flows и white-label позиционирование",
        "Собрал backend целиком: PostgreSQL, логика расписания, синхронизация с Google Calendar, напоминания",
        "Разработал Telegram Bot + Mini App frontend с UI-темами под ниши",
        "Выпустил админку, RBAC, мультиязычность и health-мониторинг",
        "Сделал интерактивное демо для презентаций и онбординга клиентов",
      ],
      results: [
        "End-to-end продукт — от идеи до деплоя",
        "Бронирование за 2–3 тапа внутри Telegram, отдельный сайт не нужен",
        "White-label темы под ниши (тренер, барбер, репетитор) — не общий шаблон",
        "Production-ready стек с автомониторингом на Railway/Vercel",
      ],
    },
  },
  "helix-trade": {
    title: "Helix Trade",
    kind: "product",
    type: "Full-Stack Product · SaaS For Sale",
    tags: ["Trading Bot", "SaaS", "Polymarket"],
    official: null,
    demo: "https://zirvey.github.io/Scalping-Bot-SaaS/",
    github: "https://github.com/Zirvey/Scalping-Bot-SaaS",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/Scalping-Bot-SaaS/main/assets/screenshots/01-helix-landing.png",
    challenge:
      "Package a Polymarket 5-minute scalping bot (BTC/ETH/SOL) as a turnkey SaaS product — with verified track record, sales deck, trader cabinet, subscription UX, and live-ready architecture for handoff.",
    approach: [
      "Designed Helix Trade brand, neon design system, landing, pricing, and auth flows",
      "Built automated scalping bot with edge-based entries, risk guards, and exit rules",
      "Developed trader cabinet: dashboard, positions, trade journal, backtest, and console",
      "Shipped subscription model UX — free trial + paid tier — and sales deck on GitHub Pages",
      "Validated strategy against 1,632 paper trades with automated metrics pipeline",
    ],
    results: [
      "Turnkey SaaS product: website + bot + dashboard + subscription UX",
      "Verified metrics: 74.6% win rate, +$533 PnL across 1,632 tracked trades",
      "Live sales deck and product UI on GitHub Pages",
      "Ready-to-launch Polymarket scalping platform for resale or own launch",
    ],
    stack: "Python, JavaScript, HTML/CSS, Polymarket API",
    role: "Product idea, trading logic, brand/UI, dashboard, data pipeline, deployment",
    ru: {
      type: "Full-Stack продукт · SaaS на продажу",
      role: "Идея продукта, торговая логика, бренд/UI, дашборд, data pipeline, деплой",
      challenge:
        "Упаковать Polymarket 5-минутный скальпинг-бот (BTC/ETH/SOL) в готовый SaaS — с проверенной статистикой, sales deck, кабинетом трейдера, подписочным UX и архитектурой, готовой к передаче.",
      approach: [
        "Спроектировал бренд Helix Trade, neon-систему, лендинг, прайсинг и auth-флоу",
        "Собрал автоскальпинг-бот с edge-входами, риск-гардами и правилами выхода",
        "Разработал кабинет трейдера: дашборд, позиции, журнал, бэктест и консоль",
        "Выпустил UX подписки — trial + paid — и sales deck на GitHub Pages",
        "Проверил стратегию на 1 632 paper-сделках с автопайплайном метрик",
      ],
      results: [
        "Готовый SaaS: сайт + бот + дашборд + подписочный UX",
        "Проверенные метрики: 74.6% win rate, +$533 PnL на 1 632 сделках",
        "Живой sales deck и UI продукта на GitHub Pages",
        "Готовая к запуску Polymarket-платформа для продажи или собственного старта",
      ],
    },
  },
  dota: {
    title: "Dota Companion",
    kind: "product",
    type: "Full-Stack Product · Private",
    tags: ["Flutter", "Mobile", "Gaming"],
    private: true,
    official: null,
    demo: null,
    github: null,
    afterImage: "projects/dota-companion.jpg",
    challenge:
      "Dota 2 players need hero meta win rates, draft assistance, and profile lookup in one fast mobile app — without juggling browser tabs and outdated third-party tools.",
    approach: [
      "Built a Flutter app from scratch: Hero Meta, Draft Assistant, and Player Profile",
      "Integrated OpenDota API for live win rates by rank bracket (Herald–Immortal)",
      "Draft module: counter picks, synergy scoring, team draft score, match import",
      "Steam ID lookup with match history; optional STRATZ API for synergy data",
      "Dark gaming UI with Riverpod state management and offline-friendly caching",
    ],
    results: [
      "Full mobile companion app — designed and developed solo",
      "Three core modules shipped: Meta, Draft, Profile",
      "Private repository — demo screenshot and walkthrough available on request",
    ],
    stack: "Flutter, Dart, Riverpod, GoRouter, OpenDota API, STRATZ API, Hive",
    role: "Product idea, UI/UX, mobile development, API integration",
    ru: {
      type: "Full-Stack продукт · Private",
      role: "Идея продукта, UI/UX, мобильная разработка, API-интеграция",
      challenge:
        "Игрокам Dota 2 нужны win rate по мете, помощь в драфте и поиск профиля в одном быстром мобильном приложении — без вкладок браузера и устаревших сторонних инструментов.",
      approach: [
        "С нуля собрал Flutter-приложение: Hero Meta, Draft Assistant и Player Profile",
        "Подключил OpenDota API для live win rate по рангам (Herald–Immortal)",
        "Модуль драфта: контрпики, синергия, командный draft score, импорт матча",
        "Поиск по Steam ID с историей матчей; опционально STRATZ API для синергии",
        "Тёмный gaming UI на Riverpod с кэшем, удобным офлайн",
      ],
      results: [
        "Полноценный мобильный companion — дизайн и разработка соло",
        "Три ключевых модуля: Meta, Draft, Profile",
        "Приватный репозиторий — скриншот и walkthrough по запросу",
      ],
    },
  },
  plantup: {
    title: "PlantUp",
    kind: "product",
    type: "Full-Stack Product · Subscription Marketplace",
    tags: ["SaaS", "Subscription", "E-commerce", "CS/RU/EN"],
    private: false,
    official: null,
    demo: "https://zirvey.github.io/PlantUp-SaaS/app/",
    github: "https://github.com/Zirvey/PlantUp-SaaS",
    afterImage: "projects/plantup.jpg",
    challenge:
      "Connect Prague residents directly with Czech farmers — a subscription club for fresh BIO produce at farmer prices, with weekly Friday delivery across Holešovice, Vinohrady, Žižkov, and Dejvice.",
    approach: [
      "Designed and built the full marketplace from idea to production",
      "Membership tiers (1 / 3 / 12 months) with eco-box options and nutrition perks",
      "Farmer showcase, product catalog with filters/sort, cart, and subscription flows",
      "Multilingual CS / RU / EN UI for local and expat audiences",
      "Plastic-free, farm-direct branding with delivery map and member stories",
    ],
    results: [
      "Public live demo of the client marketplace",
      "Complete subscription e-commerce flow — built from zero, not a redesign",
      "Open-source repo with full product surface for farmers, clients, and partners",
    ],
    stack: "Next.js, TypeScript, Tailwind CSS, GitHub Pages",
    role: "Product idea, UI/UX, frontend, backend, deployment",
    ru: {
      type: "Full-Stack продукт · Подписочный маркетплейс",
      role: "Идея продукта, UI/UX, frontend, backend, деплой",
      challenge:
        "Связать жителей Праги напрямую с чешскими фермерами — подписочный клуб свежей BIO-продукции по фермерским ценам с еженедельной пятничной доставкой по Holešovice, Vinohrady, Žižkov и Dejvice.",
      approach: [
        "Спроектировал и собрал маркетплейс от идеи до production",
        "Тарифы членства (1 / 3 / 12 месяцев) с eco-box опциями и nutrition-бонусами",
        "Витрина фермеров, каталог с фильтрами/сортировкой, корзина и подписочные флоу",
        "Мультиязычный UI CS / RU / EN для локальной и экспат-аудитории",
        "Plastic-free, farm-direct брендинг с картой доставки и историями участников",
      ],
      results: [
        "Публичное live-демо клиентского маркетплейса",
        "Полный подписочный e-commerce флоу — с нуля, не редизайн",
        "Open-source репозиторий с полной продуктовой поверхностью для фермеров, клиентов и партнёров",
      ],
    },
  },
  "devops-learn": {
    title: "DevOps Learn",
    kind: "product",
    type: "Full-Stack Product · Learning Platform",
    tags: ["React", "TypeScript", "Education"],
    official: null,
    demo: "https://zirvey.github.io/DevOps-Learn/",
    github: "https://github.com/Zirvey/DevOps-Learn",
    afterImage: "projects/devops-learn.jpg",
    challenge:
      "Junior engineers and career switchers need structured DevOps learning — not scattered blog posts. A self-paced platform with theory, exercises, progress tracking, and hands-on practice in one place.",
    approach: [
      "Structured 15 modules and 50 chapters: Linux, Git, Docker, K8s, CI/CD, Terraform, AWS, security",
      "Built bilingual RU/EN UI with chapter content switching and dark/light theme",
      "Added interactive terminal trainer for Linux and Git commands inside lessons",
      "Implemented local progress tracking, quizzes, and markdown-driven lesson content",
      "Deployed free public platform on GitHub Pages for portfolio and community use",
    ],
    results: [
      "Complete learning platform — from fundamentals to Office IT and career modules",
      "50 chapters covering DevOps, SRE, cloud, monitoring, and sysadmin topics",
      "Interactive terminal checks and progress saved in browser",
      "Live at zirvey.github.io/DevOps-Learn",
    ],
    stack: "React 19, TypeScript, Vite, React Router, React Markdown",
    role: "Product idea, curriculum, UI/UX, frontend, deployment",
    ru: {
      type: "Full-Stack продукт · Обучающая платформа",
      role: "Идея продукта, учебная программа, UI/UX, frontend, деплой",
      challenge:
        "Джунам и людям, меняющим карьеру, нужно структурированное изучение DevOps — не разрозненные статьи. Self-paced платформа с теорией, упражнениями, прогрессом и практикой в одном месте.",
      approach: [
        "Структурировал 15 модулей и 50 глав: Linux, Git, Docker, K8s, CI/CD, Terraform, AWS, security",
        "Собрал двуязычный RU/EN UI с переключением контента глав и dark/light темой",
        "Добавил интерактивный terminal trainer для команд Linux и Git внутри уроков",
        "Реализовал локальный трекинг прогресса, квизы и markdown-контент уроков",
        "Развернул бесплатную публичную платформу на GitHub Pages",
      ],
      results: [
        "Полная обучающая платформа — от основ до Office IT и карьерных модулей",
        "50 глав по DevOps, SRE, cloud, мониторингу и sysadmin",
        "Интерактивные проверки в терминале и прогресс в браузере",
        "Live на zirvey.github.io/DevOps-Learn",
      ],
    },
  },
};
