export const caseStudies = {
  "w-steak": {
    title: "W Steak Restaurant",
    kind: "concept",
    type: "UI/UX Redesign Concept",
    tags: ["HTML", "Dark & Gold", "Hospitality"],
    official: "https://wrestaurant.cz/",
    beforeImage: "case-studies/before-w-steak.jpg",
    demo: "https://zirvey.github.io/w-steak-restaurant-landing-page/",
    github: "https://github.com/Zirvey/w-steak-restaurant-landing-page",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/w-steak-restaurant-landing-page/main/docs/screenshots/hero-desktop.jpg",
    challenge:
      "The official W Steak Restaurant site carries strong brand recognition but the landing experience felt dated — dense layout, limited visual hierarchy, and a mobile experience that didn't match the premium positioning of a steak & whiskey bar in Prague.",
    approach: [
      "Audited the original wrestaurant.cz structure, menu flow, and reservation path",
      "Defined a dark & gold design system aligned with the restaurant's premium identity",
      "Built a bento-grid hero, experience section, menu highlights, and about block",
      "Prioritised mobile-first responsive layout with clear CTAs for reservations",
    ],
    results: [
      "Cohesive premium dark aesthetic with gold accent system",
      "Clear information hierarchy from hero → experience → menu → contact",
      "Fully responsive concept deployed to GitHub Pages",
      "Reused official photography and menu data for realistic demonstration",
    ],
    stack: "HTML, CSS, Vanilla JS",
  },
  smokehouse: {
    title: "Smokehouse Prague",
    kind: "concept",
    type: "UI/UX Redesign Concept",
    tags: ["Next.js", "Framer Motion", "Hospitality"],
    official: "https://www.smokehouse.cz/",
    beforeImage: "case-studies/before-smokehouse.jpg",
    demo: "https://zirvey.github.io/smokehouse-desing/",
    github: "https://github.com/Zirvey/smokehouse-desing",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/smokehouse-desing/main/docs/hero.png",
    challenge:
      "Smokehouse operates three Prague locations with a loyal audience, but the existing website didn't convey the lounge's premium atmosphere — navigation was cluttered and animations were absent, making the brand feel static online.",
    approach: [
      "Studied smokehouse.cz content architecture across locations and loyalty program",
      "Preserved Czech copy and original brand assets for authenticity",
      "Designed scroll-driven sections: hero, features, locations, loyalty, CTA",
      "Implemented Framer Motion micro-interactions and Tailwind v4 layout system",
    ],
    results: [
      "Modern dark lounge aesthetic with gold accents and smooth entrance animations",
      "Multi-location content organised in a scannable layout",
      "Production-grade Next.js 15 + TypeScript codebase with CI pipeline",
      "Deployed live demo on GitHub Pages",
    ],
    stack: "Next.js 15, TypeScript, Tailwind CSS v4, Framer Motion",
  },
  "smoky-place": {
    title: "Smoky Place",
    kind: "concept",
    type: "UI/UX Redesign Concept",
    tags: ["HTML", "Dark & Red", "Hospitality"],
    official: "https://smokyplace.cz/",
    beforeImage: "case-studies/before-smoky-place.jpg",
    demo: "https://zirvey.github.io/smoky-place-landing-page/",
    github: "https://github.com/Zirvey/smoky-place-landing-page",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/smoky-place-landing-page/main/docs/screenshots/hero.png",
    challenge:
      "Smoky Place is a hookah lounge at Prague Chodov with a distinctive brand, but the current site lacked visual impact — key offerings like the VIP lounge, events, and reviews were buried without strong calls to action.",
    approach: [
      "Mapped smokyplace.cz user journey: discovery → menu → VIP lounge → booking",
      "Created a red-accent dark theme with glowing coal hero imagery",
      "Designed dedicated sections for menu, private lounge, events calendar, and reviews carousel",
      "Built reservation modal and sticky navigation for mobile users",
    ],
    results: [
      "Premium hookah lounge feel with red & gold accent palette",
      "VIP lounge and events promoted as first-class sections",
      "Czech-localised content with scroll animations and responsive layout",
      "Live GitHub Pages demo ready for portfolio presentation",
    ],
    stack: "HTML, CSS, Vanilla JS",
  },
  booking: {
    title: "Booking Telegram App",
    kind: "product",
    type: "Full-Stack Product",
    tags: ["Telegram Mini App", "PostgreSQL", "White-label"],
    official: null,
    demo: "https://zirvey.github.io/Booking-Telegram-App-Prewiev/",
    github: "https://github.com/Zirvey/Booking-Telegram-App-Prewiev",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/Booking-Telegram-App-Prewiev/main/docs/screenshots/general/hero-banner.png",
    challenge:
      "Service businesses — trainers, barbers, tutors, therapists — lose clients in messy DMs and miss appointments. They need a turnkey booking system without hiring a dev team or building a website from scratch.",
    approach: [
      "Defined the product idea, user flows, and white-label positioning from scratch",
      "Built the full backend: PostgreSQL, scheduling logic, Google Calendar sync, reminders",
      "Developed Telegram Bot + Mini App frontend with niche-specific UI themes",
      "Shipped admin panel, role-based access, multi-language support, and health monitoring",
      "Created an interactive demo site for client presentations and onboarding",
    ],
    results: [
      "End-to-end product — from idea to deployable solution",
      "2–3 tap booking flow inside Telegram, no separate website required",
      "White-label themes per niche (trainer, barber, tutor) — not a generic template",
      "Production-ready stack with automated monitoring on Railway/Vercel",
    ],
    stack: "Telegram Bot API, Mini App, PostgreSQL, Google Calendar, Python, Vercel",
    role: "Product idea, UI/UX, backend, frontend, deployment",
  },
  "ev-scalp": {
    title: "EV Scalp Pro",
    kind: "product",
    type: "Full-Stack Product",
    tags: ["Trading Bot", "SaaS", "Dashboard"],
    official: null,
    demo: "https://zirvey.github.io/Scalping-Bot-SaaS/demo/",
    github: "https://github.com/Zirvey/Scalping-Bot-SaaS",
    afterImage:
      "https://raw.githubusercontent.com/Zirvey/Scalping-Bot-SaaS/main/assets/screenshots/01-hero-dashboard.png",
    challenge:
      "Build a complete scalping bot for Polymarket 5-minute markets (BTC/ETH/SOL) and package it as a sellable product — with real trading logic, performance data, and a professional UI layer for demos and handoff.",
    approach: [
      "Designed the trading strategy, signal funnel, and exit logic from the ground up",
      "Built and tested the bot against 432 real trades — journal, backtest, metrics pipeline",
      "Created a SaaS sales landing page and interactive dashboard mirroring the live bot UI",
      "Developed backtest, console, settings, and trade history views with real performance data",
      "Automated chart generation from canonical metrics for always-accurate reporting",
    ],
    results: [
      "Full product: bot logic + dashboard + sales deck — built solo",
      "Verified metrics: 75% win rate, +$105 PnL across 432 tracked trades",
      "Interactive demo dashboard deployed on GitHub Pages for client handoff",
      "Ready-to-launch turnkey solution for Polymarket scalping",
    ],
    stack: "Python, JavaScript, HTML/CSS, PostgreSQL, Polymarket API",
    role: "Product idea, trading logic, UI/dashboard, data pipeline, deployment",
  },
  dota: {
    title: "Dota Companion",
    kind: "product",
    type: "Full-Stack Product · Private",
    tags: ["Flutter", "Mobile", "Gaming"],
    private: true,
    official: null,
    demo: null,
    github: null,
    afterImage: "projects/dota-companion.jpg",
    challenge:
      "Dota 2 players need hero meta win rates, draft assistance, and profile lookup in one fast mobile app — without juggling browser tabs and outdated third-party tools.",
    approach: [
      "Built a Flutter app from scratch: Hero Meta, Draft Assistant, and Player Profile",
      "Integrated OpenDota API for live win rates by rank bracket (Herald–Immortal)",
      "Draft module: counter picks, synergy scoring, team draft score, match import",
      "Steam ID lookup with match history; optional STRATZ API for synergy data",
      "Dark gaming UI with Riverpod state management and offline-friendly caching",
    ],
    results: [
      "Full mobile companion app — designed and developed solo",
      "Three core modules shipped: Meta, Draft, Profile",
      "Private repository — demo screenshot and walkthrough available on request",
    ],
    stack: "Flutter, Dart, Riverpod, GoRouter, OpenDota API, STRATZ API, Hive",
    role: "Product idea, UI/UX, mobile development, API integration",
  },
  biomark: {
    title: "BioMarket",
    kind: "product",
    type: "Full-Stack Product",
    tags: ["Next.js", "Subscription", "E-commerce"],
    private: true,
    official: null,
    demo: "https://biomark-web.vercel.app/",
    github: null,
    afterImage: "projects/biomark-web.jpg",
    challenge:
      "Connect Prague residents directly with Czech farmers — a subscription club for fresh BIO produce at farmer prices, with weekly delivery across Holešovice, Vinohrady, Žižkov, and Dejvice.",
    approach: [
      "Designed and built the full web platform from idea to production on Vercel",
      "Membership tiers (1 / 3 / 12 months) with eco-box options and nutrition perks",
      "Farmer showcase, product catalog with filters, and subscription checkout flow",
      "Russian-localised UI for the target market; plastic-free, farm-direct branding",
      "End-to-end: frontend, backend logic, payments integration, deployment",
    ],
    results: [
      "Live production site serving Prague districts",
      "Complete subscription e-commerce flow — not a redesign, built from zero",
      "Private repository; public demo at biomark-web.vercel.app",
    ],
    stack: "Next.js, TypeScript, Tailwind CSS, Vercel",
    role: "Product idea, UI/UX, frontend, backend, deployment",
  },
  parser: {
    title: "Website Lead Parser",
    kind: "tool",
    type: "Automation Tool",
    tags: ["Python", "Web Scraping", "Lead Scoring"],
    private: true,
    official: null,
    demo: null,
    github: null,
    afterImage: null,
    challenge:
      "Freelance and outreach work needs a steady pipeline of potential clients — specifically businesses in the Czech market running websites with outdated design that could benefit from a modern rebuild.",
    approach: [
      "Built a Python parser to crawl and analyse .cz websites at scale",
      "Designed scoring heuristics to flag outdated layouts, old tech stacks, and poor mobile UX",
      "Automated scheduled runs with structured output for lead prioritisation",
      "Connected results to a workflow for targeted outreach and redesign proposals",
    ],
    results: [
      "Automated lead generation — replaces manual browsing of hundreds of sites",
      "Directly fed into UI/UX redesign freelance pipeline",
      "Demonstrates automation + business thinking beyond pure design work",
    ],
    stack: "Python, web scraping, scheduled jobs, REST APIs",
    role: "Tool design, scripting, automation pipeline",
  },
};
